### ISSUE TITLE
An error occurred while resolving packages:

### ISSUE THREAD

**Issue by ltonial** [GameWorkstore/patterns#1]
Project has invalid dependencies:
    com.gameworkstore.patterns: Error when executing git command. fatal: remote error: 
      The unauthenticated git protocol on port 9418 is no longer supported.
    Please see https://github.blog/2021-09-01-improving-git-protocol-security-github/ for more information.

**Comment by HanzaRu** [comment]
Hey @ltonial, you're right! Unity has changed the way that GitHub packages can be imported into projects. Now you need to use 

"com.gameworkstore.patterns": "https://github.com/GameWorkstore/patterns.git#1.1.2"

instead of 

"com.gameworkstore.patterns": "git://github.com/GameWorkstore/patterns.git#1.1.2"

---

I already changed it on README.md, if you find any other issues, let me know! If that is all, can you close the issue?

Cheers,
Hanza
